---
apiVersion: v1
kind: Service
metadata:
  name: websocket-service
  namespace: websocket
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    name: websocket-app
