---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      name: api-gateway
  template:
    metadata:
      labels:
        name: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: metinagaoglu/example-api-gateway:1.2
          env:
            - name: REDIS_HOST
              value: "svc-redis.redis-cluster.svc.cluster.local:6379"
            - name: PORT
              value: ":3000"
            - name: AUTH_SVC_URL
              value: localhost:50051
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000