---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: api-gateway
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    name: api-gateway
