apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  namespace: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:latest
        ports:
        - containerPort: 5672  # RabbitMQ default port
        - containerPort: 15672 # RabbitMQ management plugin port
        env:
        - name: RABBITMQ_ERLANG_COOKIE
          value: "cookiemonster"  # Change this to a secure value
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: rabbitmq
spec:
  ports:
  - port: 5672
