apiVersion: v1
kind: Namespace
metadata:
  name: websocket
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-gateway
  namespace: websocket
spec:
  replicas: 2
  selector:
    matchLabels:
      name: websocket-gateway
  template:
    metadata:
      labels:
        name: websocket-gateway
    spec:
      containers:
        - name: application
          image: metinagaoglu/go-websocket:1.4
          env:
            - name: REDIS_HOST
              value: "svc-redis.redis-cluster.svc.cluster.local:6379"
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq-service.rabbitmq:5672"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
---
## new alpine deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine
  namespace: websocket
spec:
  replicas: 1
  selector:
    matchLabels:
      name: alpine
  template:
    metadata:
      labels:
        name: alpine
    spec:
      containers:
        - name: alpine
          image: alpine:latest
          command: ["/bin/sh"]
          args: ["-c", "apk add --no-cache curl && sleep 3600"]
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-service
  namespace: websocket
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 8000
  selector:
    name: websocket-gateway