version: '3'
services:
  websocket-gateway:
    build:
      context: ../services/websocket-gateway
      dockerfile: Dockerfile
    ports:
      - 3000:8000
    volumes:
      - ../services/websocket-gateway/:/go/src/app
  api-gateway:
    build:
      context: ../services/api-gateway
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    volumes:
      - ../services/api-gateway/:/go/src/app
  auth-service:
    build:
      context: ../services/auth-service
      dockerfile: Dockerfile
    ports:
      - 3002:3000
    volumes:
      - ../services/auth-service/:/go/src/app
  session-service:
    build:
      context: ../services/session-service
      dockerfile: Dockerfile
    ports:
      - 3003:3000
    volumes:
      - ../services/session-service/:/go/src/app