version: '3'
services:
  websocket-gateway:
    build:
      context: ../src/websocket-gateway
      dockerfile: Dockerfile
    ports:
      - 3000:8000
    volumes:
      - ../src/websocket-gateway/:/go/src/app
  api-gateway:
    build:
      context: ../src/api-gateway
      dockerfile: Dockerfile
    ports:
      - 3001:3000
  auth-service:
    build:
      context: ../src/auth-service
      dockerfile: Dockerfile
    ports:
      - 3002:3000
  session-service:
    build:
      context: ../src/session-service
      dockerfile: Dockerfile
    ports:
      - 3003:3000